version: "3"

services:
  flask:
    build: ./flask
    container_name: fyc_flask
    ports:
      - 3000:3000
    command: gunicorn --worker-class eventlet -b 0.0.0.0:3000 run:app

  nginx:
    build: ./nginx
    container_name: fyc_nginx
    depends_on:
      - flask
    volumes:
      - /home/ubuntu/find-your-consultant/flask/app/static:/static
    ports:
      - 80:80
      - 443:443