version: "3"

services:
  flask:
    build: ./flask
    container_name: fyc_flask

  nginx:
    build: ./nginx
    container_name: fyc_nginx
    depends_on:
      - flask
    ports:
      - 80:80
      - 443:443